### ISSUE TITLE
Issue Installing Latest Update via CKAN

### ISSUE THREAD

**Issue by AEWorthy** [KSP-RO/RealismOverhaul#1080]
I'm not sure if this is a problem with CKAN, RO, or a conflicting mod, but this error is being thrown when I try to check the update box, or try to uninstall Realism Overhaul through CKAN:

> CKAN.ModuleNotFoundKraken: Cannot install CrossFeedEnabler, module not available
   at CKAN.CkanModule.FromIDandVersion(IRegistryQuerier registry, String mod, KSPVersion ksp_version)
   at CKAN.RelationshipResolver.<RelationshipResolver>c__AnonStorey0.<>m__0(String name)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CKAN.RelationshipResolver..ctor(IEnumerable`1 module_names, RelationshipResolverOptions options, IRegistryQuerier registry, KSPVersion kspversion)
   at CKAN.MainModList.ComputeConflictsFromModList(IRegistryQuerier registry, IEnumerable`1 change_set, KSPVersion ksp_version)
   at CKAN.Main.<UpdateChangeSetAndConflicts>c__async1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKAN.Main.<ModList_CellValueChanged>c__async0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

Any help would be much appreciated. Thank you

**Comment by NathanKell** [comment]
This is an issue with some mod requiring CrossFeedEnabler, but CrossFeedEnabler not being a mod for 1.0.5. I suggest checking your list (and maybe posting an issue on the CKAN-meta repo) about it, to try to find out what's requiring it. Maybe B9 Proc Parts/Proc Wings? If so, its netkan needs updating.
